from radcraft_compiler.fluka_cards import (
    AssignMatCard,
    BeamCard,
    BeamPosCard,
    DefaultsCard,
    FlukaCard,
    RandomizeCard,
    StartCard,
    StopCard,
    UsrbinCard,
    render_comment,
)


def test_base_card_rendering_is_stable() -> None:
    assert FlukaCard("TEST", fields=(1, 2.5, "ABC"), sdum="TAG").render() == (
        "TEST               1       2.5       ABC                              TAG"
    )


def test_float_fields_fit_fixed_width_columns() -> None:
    rendered = FlukaCard("TEST", fields=(153.333333, -0.63267449, -0.44659376)).render()

    assert all(len(rendered[start : start + 10].strip()) <= 10 for start in range(10, 40, 10))


def test_comment_rendering() -> None:
    assert render_comment("generated by Oops-enheimer") == "* generated by Oops-enheimer"


def test_core_cards_render_expected_keywords() -> None:
    assert DefaultsCard().render().startswith("DEFAULTS")
    assert "PRECISIO" in DefaultsCard().render()
    assert "PHOTON" in BeamCard("photon", 0.001).render()
    assert "NEUTRON" in BeamCard("NEUTRON", 0.001).render()
    assert BeamPosCard((1, 2, 3), (0, 0, 1)).render() == (
        "BEAMPOS            1         2         3"
    )
    angled_beam = BeamPosCard((1, 2, 3), (0.3, 0.4, 0.8660254)).render()
    assert angled_beam == "BEAMPOS            1         2         3       0.3       0.4"
    negative_z_beam = BeamPosCard((1, 2, 3), (0.3, 0.4, -0.8660254)).render()
    assert negative_z_beam.endswith("NEGATIVE")
    assert "       0.3       0.4" in negative_z_beam
    assert "0.8660254" not in negative_z_beam
    horizontal_beam = BeamPosCard((1, 2, 3), (1, 0, 0)).render()
    assert "0.99999998" in horizontal_beam
    assert "ASSIGNMA" in AssignMatCard("LEAD", "VOXEL002").render()
    assert "RANDOMIZ" in RandomizeCard(12345).render()
    assert "START" in StartCard(100000).render()
    assert StopCard().render() == "STOP"


def test_usrbin_renders_three_stable_lines() -> None:
    rendered = UsrbinCard(
        quantity="DOSE",
        name="dose_map",
        mesh_id=21,
        lower_cm=(0, 0, 0),
        upper_cm=(160, 80, 80),
        bins=(32, 16, 16),
    ).render()

    lines = rendered.splitlines()
    assert len(lines) == 2
    assert lines[0].startswith("USRBIN")
    assert "DOSE" in lines[0]
    assert "dose_map" in lines[0]
    assert "160" in lines[0]
    assert "32" in lines[1]
    assert "&" in lines[1]
