"""Emit minimal FLUKA input files for Oops-enheimer scenes."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from oopsenheimer_compiler.compiler import expand_chunks, resolve_materials
from oopsenheimer_compiler.fluka_cards import (
    AssignMatCard,
    BeamCard,
    BeamPosCard,
    CompoundCard,
    DefaultsCard,
    MaterialCard,
    RandomizeCard,
    StartCard,
    StopCard,
    UsrbinCard,
    render_comment,
)
from oopsenheimer_compiler.organ_map import OrganMap
from oopsenheimer_compiler.schema import SceneDefinition


@dataclass(frozen=True)
class GeometryRegion:
    name: str
    material_id: str


@dataclass(frozen=True)
class GeometryRender:
    lines: list[str]
    regions: list[GeometryRegion]


@dataclass(frozen=True)
class MaterialCuboid:
    material_id: str
    min_index: tuple[int, int, int]
    max_index: tuple[int, int, int]


Bounds = tuple[float, float, float, float, float, float]
CompoundComponents = tuple[tuple[float, str], ...]

ELEMENT_MATERIALS: dict[str, tuple[float, float]] = {
    "HYDROGEN": (1.0, 8.3748e-5),
    "CARBON": (6.0, 2.265),
    "NITROGEN": (7.0, 0.0011653),
    "OXYGEN": (8.0, 0.001429),
    "SODIUM": (11.0, 0.971),
    "MAGNESIU": (12.0, 1.74),
    "ALUMINUM": (13.0, 2.6989),
    "SILICON": (14.0, 2.33),
    "POTASSIU": (19.0, 0.862),
    "CALCIUM": (20.0, 1.55),
    "IRON": (26.0, 7.874),
}

CUSTOM_COMPOUND_MATERIALS: dict[str, tuple[float, CompoundComponents]] = {
    "CONCRETE": (
        2.35,
        (
            (-0.01, "HYDROGEN"),
            (-0.001, "CARBON"),
            (-0.529107, "OXYGEN"),
            (-0.016, "SODIUM"),
            (-0.002, "MAGNESIU"),
            (-0.033872, "ALUMINUM"),
            (-0.337021, "SILICON"),
            (-0.013, "POTASSIU"),
            (-0.044, "CALCIUM"),
            (-0.014, "IRON"),
        ),
    ),
    "WOOD": (
        0.7,
        (
            (-0.444, "CARBON"),
            (-0.062, "HYDROGEN"),
            (-0.494, "OXYGEN"),
        ),
    ),
    "GLASS": (
        2.5,
        (
            (-0.459, "OXYGEN"),
            (-0.337, "SILICON"),
            (-0.097, "SODIUM"),
            (-0.107, "CALCIUM"),
        ),
    ),
    "TISSUE": (
        1.0,
        (
            (-0.101, "HYDROGEN"),
            (-0.111, "CARBON"),
            (-0.026, "NITROGEN"),
            (-0.762, "OXYGEN"),
        ),
    ),
    "STEEL": (
        7.85,
        (
            (-0.985, "IRON"),
            (-0.015, "CARBON"),
        ),
    ),
    "RUBBER": (
        1.1,
        (
            (-0.87, "CARBON"),
            (-0.13, "HYDROGEN"),
        ),
    ),
    "PLASTIC": (
        0.95,
        (
            (-0.856, "CARBON"),
            (-0.144, "HYDROGEN"),
        ),
    ),
}


def render_inp(scene: SceneDefinition, organ_map: OrganMap) -> str:
    """Render a minimal FLUKA input deck.

    Generic voxel scenes are emitted as FLUKA combinatorial geometry: the dense
    material grid is greedily merged into disjoint rectangular parallelepipeds,
    and each cuboid is assigned to its material as an independent region.
    """
    lines: list[str] = [
        render_comment("Generated by Oops-enheimer."),
        "TITLE",
        scene.emit.fluka_input.title,
        DefaultsCard(scene.run.defaults).render(),
    ]
    lines.extend(_render_custom_material_definitions(scene))

    if scene.sources:
        source = scene.sources[0]
        lines.extend(
            [
                BeamCard(source.particle, source.energy_gev).render(),
                render_comment("Beam direction is encoded with BEAMPOS transverse cosines and z sign."),
                BeamPosCard(source.position_cm, source.direction).render(),
            ]
        )

    geometry = _render_geometry(scene)
    lines.extend(geometry.lines)

    for region in geometry.regions:
        material = scene.materials[region.material_id]
        if material.fluka_name is None:
            raise ValueError(f"materialId '{region.material_id}' is missing flukaName")
        lines.append(AssignMatCard(material.fluka_name, region.name).render())

    for mesh_id, scoring in enumerate(scene.scoring, start=21):
        lines.append(
            UsrbinCard(
                quantity=scoring.quantity,
                name=scoring.id,
                mesh_id=mesh_id,
                lower_cm=scoring.min_cm,
                upper_cm=scoring.max_cm,
                bins=scoring.dims,
            ).render()
        )

    lines.extend(
        [
            RandomizeCard(scene.run.random_seed).render(),
            StartCard(scene.run.histories).render(),
            StopCard().render(),
        ]
    )
    return "\n".join(lines) + "\n"


def _render_custom_material_definitions(scene: SceneDefinition) -> list[str]:
    rendered: list[str] = []
    custom_materials: dict[str, tuple[float, CompoundComponents]] = {}
    for _material_id, material in sorted(scene.materials.items()):
        if not material.fluka_name:
            continue
        material_name = material.fluka_name.upper()
        if material_name in custom_materials or material_name not in CUSTOM_COMPOUND_MATERIALS:
            continue

        default_density, components = CUSTOM_COMPOUND_MATERIALS[material_name]
        density = material.density_g_cm3 or material.density or default_density
        custom_materials[material_name] = (density, components)

    component_names = sorted(
        {
            component_name
            for _density, components in custom_materials.values()
            for _fraction, component_name in components
        }
    )
    for component_name in component_names:
        atomic_number, density = ELEMENT_MATERIALS[component_name]
        rendered.append(MaterialCard(component_name, density, atomic_number=atomic_number).render())

    for material_name, (density, components) in sorted(custom_materials.items()):
        rendered.append(MaterialCard(material_name, density).render())
        for component_group in _chunk_compound_components(components):
            rendered.append(CompoundCard(material_name, component_group).render())
    return rendered


def _chunk_compound_components(
    components: CompoundComponents,
) -> list[CompoundComponents]:
    return [components[index : index + 3] for index in range(0, len(components), 3)]


def emit_inp(scene: SceneDefinition, organ_map: OrganMap, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_inp(scene, organ_map))
    return output_path


def _render_geometry(scene: SceneDefinition) -> GeometryRender:
    if scene.world.id == "lead_wall_demo":
        return _render_lead_wall_geometry(scene)

    return _render_generic_voxel_geometry(scene)


def _render_lead_wall_geometry(scene: SceneDefinition) -> GeometryRender:
    nx, ny, nz = scene.world.grid.dims
    dx, dy, dz = scene.world.grid.voxel_size_cm
    ox, oy, oz = scene.world.grid.origin_cm
    world_max_x = ox + nx * dx
    world_max_y = oy + ny * dy
    world_max_z = oz + nz * dz
    world_bounds = (ox, world_max_x, oy, world_max_y, oz, world_max_z)
    air_bounds, blackhole_bounds = _boundary_bounds(scene, world_bounds)

    # The first demo RLE places the lead wall at z indices 7..7.
    lead_min_z = oz + 7 * dz
    lead_max_z = lead_min_z + dz

    return GeometryRender(
        lines=[
            "GEOBEGIN                                                              COMBNAME",
            "  0 0                       Oops-enheimer lead wall demo geometry",
            _format_rpp_from_bounds("BLKBODY", blackhole_bounds),
            _format_rpp_from_bounds("AIRBOX", air_bounds),
            _format_rpp("WORLD", ox, world_max_x, oy, world_max_y, oz, world_max_z),
            _format_rpp("LEADWALL", ox, world_max_x, oy, world_max_y, lead_min_z, lead_max_z),
            "END",
            "BLKBODY 5 +BLKBODY -AIRBOX",
            "EXTAIR  5 +AIRBOX -WORLD",
            "AIRREG  5 +WORLD -LEADWALL",
            "LEADREG 5 +LEADWALL",
            "END",
            "GEOEND",
            AssignMatCard("BLCKHOLE", "BLKBODY").render(),
        ],
        regions=[
            GeometryRegion(name="EXTAIR", material_id=scene.world.boundary.outside_material_id),
            GeometryRegion(name="AIRREG", material_id="air"),
            GeometryRegion(name="LEADREG", material_id="lead"),
        ],
    )


def _render_generic_voxel_geometry(scene: SceneDefinition) -> GeometryRender:
    material_grid = resolve_materials(scene, expand_chunks(scene)).material_grid
    cuboids = material_cuboids_from_grid(material_grid)
    nx, ny, nz = scene.world.grid.dims
    dx, dy, dz = scene.world.grid.voxel_size_cm
    ox, oy, oz = scene.world.grid.origin_cm
    world_max_x = ox + nx * dx
    world_max_y = oy + ny * dy
    world_max_z = oz + nz * dz
    world_bounds = (ox, world_max_x, oy, world_max_y, oz, world_max_z)
    air_bounds, blackhole_bounds = _boundary_bounds(scene, world_bounds)

    body_lines = [
        "GEOBEGIN                                                              COMBNAME",
        f"  0 0                       Oops-enheimer voxel cuboid geometry ({len(cuboids)} regions)",
        _format_rpp_from_bounds("BLKBODY", blackhole_bounds),
        _format_rpp_from_bounds("AIRBOX", air_bounds),
        _format_rpp("WORLD", ox, world_max_x, oy, world_max_y, oz, world_max_z),
    ]

    regions: list[GeometryRegion] = [
        GeometryRegion(name="EXTAIR", material_id=scene.world.boundary.outside_material_id)
    ]
    region_lines = ["END", "BLKBODY 5 +BLKBODY -AIRBOX", "EXTAIR  5 +AIRBOX -WORLD"]

    for index, cuboid in enumerate(cuboids, start=1):
        region_name = f"R{index:06d}"
        body_name = "WORLD" if _cuboid_covers_world(cuboid, (nx, ny, nz)) else f"B{index:06d}"
        if body_name != "WORLD":
            body_lines.append(_format_cuboid_body(body_name, cuboid, (ox, oy, oz), (dx, dy, dz)))
        region_lines.append(f"{region_name} 5 +{body_name}")
        regions.append(GeometryRegion(name=region_name, material_id=cuboid.material_id))

    return GeometryRender(
        lines=[
            *body_lines,
            *region_lines,
            "END",
            "GEOEND",
            AssignMatCard("BLCKHOLE", "BLKBODY").render(),
        ],
        regions=regions,
    )


def material_cuboids_from_grid(material_grid: np.ndarray) -> list[MaterialCuboid]:
    """Greedily merge a ``grid[z, y, x]`` material grid into disjoint cuboids."""
    if material_grid.ndim != 3:
        raise ValueError(f"material_grid must be 3D, got shape {material_grid.shape}")

    nz, ny, nx = material_grid.shape
    visited = np.zeros(material_grid.shape, dtype=bool)
    cuboids: list[MaterialCuboid] = []

    for z in range(nz):
        for y in range(ny):
            for x in range(nx):
                if visited[z, y, x]:
                    continue

                material_id = str(material_grid[z, y, x])
                x1 = x + 1
                while x1 < nx and not visited[z, y, x1] and material_grid[z, y, x1] == material_id:
                    x1 += 1

                y1 = y + 1
                while y1 < ny and _can_extend_y(material_grid, visited, material_id, z, y1, x, x1):
                    y1 += 1

                z1 = z + 1
                while z1 < nz and _can_extend_z(material_grid, visited, material_id, z1, y, y1, x, x1):
                    z1 += 1

                visited[z:z1, y:y1, x:x1] = True
                cuboids.append(
                    MaterialCuboid(
                        material_id=material_id,
                        min_index=(x, y, z),
                        max_index=(x1, y1, z1),
                    )
                )

    return cuboids


def _can_extend_y(
    material_grid: np.ndarray,
    visited: np.ndarray,
    material_id: str,
    z: int,
    y: int,
    x0: int,
    x1: int,
) -> bool:
    material_slice = material_grid[z, y, x0:x1]
    visited_slice = visited[z, y, x0:x1]
    return bool(np.all(material_slice == material_id) and not np.any(visited_slice))


def _can_extend_z(
    material_grid: np.ndarray,
    visited: np.ndarray,
    material_id: str,
    z: int,
    y0: int,
    y1: int,
    x0: int,
    x1: int,
) -> bool:
    material_slice = material_grid[z, y0:y1, x0:x1]
    visited_slice = visited[z, y0:y1, x0:x1]
    return bool(np.all(material_slice == material_id) and not np.any(visited_slice))


def _cuboid_covers_world(cuboid: MaterialCuboid, dims: tuple[int, int, int]) -> bool:
    return cuboid.min_index == (0, 0, 0) and cuboid.max_index == dims


def _format_cuboid_body(
    body_name: str,
    cuboid: MaterialCuboid,
    origin_cm: tuple[float, float, float],
    voxel_size_cm: tuple[float, float, float],
) -> str:
    x0, y0, z0 = cuboid.min_index
    x1, y1, z1 = cuboid.max_index
    ox, oy, oz = origin_cm
    dx, dy, dz = voxel_size_cm
    return _format_rpp(
        body_name,
        ox + x0 * dx,
        ox + x1 * dx,
        oy + y0 * dy,
        oy + y1 * dy,
        oz + z0 * dz,
        oz + z1 * dz,
    )


def _format_rpp(
    name: str,
    x_min: float,
    x_max: float,
    y_min: float,
    y_max: float,
    z_min: float,
    z_max: float,
) -> str:
    return (
        f"RPP {name} {x_min:.8g} {x_max:.8g} "
        f"{y_min:.8g} {y_max:.8g} {z_min:.8g} {z_max:.8g}"
    )


def _boundary_bounds(scene: SceneDefinition, world_bounds: Bounds) -> tuple[Bounds, Bounds]:
    air_margin = max(float(scene.world.boundary.world_air_margin_cm), 1.0)
    blackhole_margin = max(float(scene.world.boundary.blackhole_margin_cm), air_margin + 50.0)
    air_bounds = _expand_bounds(world_bounds, air_margin)
    for source in scene.sources:
        air_bounds = _include_point(air_bounds, source.position_cm, padding=1.0)

    blackhole_padding = max(blackhole_margin - air_margin, 1.0)
    return air_bounds, _expand_bounds(air_bounds, blackhole_padding)


def _expand_bounds(bounds: Bounds, margin: float) -> Bounds:
    x_min, x_max, y_min, y_max, z_min, z_max = bounds
    return (
        x_min - margin,
        x_max + margin,
        y_min - margin,
        y_max + margin,
        z_min - margin,
        z_max + margin,
    )


def _include_point(bounds: Bounds, point: tuple[float, float, float], padding: float) -> Bounds:
    x_min, x_max, y_min, y_max, z_min, z_max = bounds
    x, y, z = point
    return (
        min(x_min, x - padding),
        max(x_max, x + padding),
        min(y_min, y - padding),
        max(y_max, y + padding),
        min(z_min, z - padding),
        max(z_max, z + padding),
    )


def _format_rpp_from_bounds(name: str, bounds: Bounds) -> str:
    return _format_rpp(name, *bounds)
